spring:
    datasource:
#        url: jdbc:mysql://localhost:3306/hsweb3?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
        url : jdbc:h2:file:./data/h2db
        username : sa
        password :
logging:
  level:
    org.hswebframework: DEBUG
    org.hswebframework.expands: ERROR
    access-logger: INFO
hsweb:
  authorize:
    auto-parse: true
    sync: true

swagger:
  title: hsweb 3.0 api
  description: hsweb 企业后台管理基础框架
  version: 3.0
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: http://www.hsweb.me/
  contact:
    name: zhouhao
    url: https://github.com/zhou-hao
    email: i@hsweb.me
  base-package: org.hswebframework.web